baseURL: '/'
title: Espaço Mithari
theme: meghna
paginate: '6'
summaryLength: '15'
disqusShortname: ''
disableLanguages: []
params:
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/themify-icons/themify-icons.css
      - link: plugins/magnific-popup/magnific-popup.css
      - link: plugins/slick/slick.css
      - link: >-
          https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap
    js:
      - link: plugins/jquery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/magnific-popup/jquery.magnific-popup.min.js
      - link: plugins/lazy-load/lozad.min.js
      - link: plugins/google-map/map.js
  logo: images/logo.png
  description: Responsive Multipurpose Parallax Hugo Template
  author: Stephanie de Castro
  email: stephaniecastron@hotmail.com
  google_analytics_id: ''
  post_share: true
  preloader:
    enable: false
    preloader: images/logo.png
  cookies:
    enable: false
    expire_days: 2
  map:
    enable: false
    gmap_api: >-
      https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ
    map_latitude: '51.5223477'
    map_longitude: '-0.1622023'
    map_marker: images/marker.png
  social:
    - icon: ti-facebook
      link: '#'
    - icon: ti-twitter-alt
      link: '#'
    - icon: ti-youtube
      link: '#'
    - icon: ti-linkedin
      link: '#'
    - icon: ti-dribbble
      link: '#'
    - icon: ti-pinterest
      link: '#'
menu:
  main:
    - name: about
      pre: '#'
      url: about
      weight: 1
    - name: services
      pre: '#'
      url: services
      weight: 2
    - name: portfolio
      pre: '#'
      url: portfolio
      weight: 3
    - name: team
      pre: '#'
      url: team
      weight: 4
    - name: pricing
      pre: '#'
      url: pricing
      weight: 5
    - name: blog
      pre: '#'
      url: blog
      weight: 6
    - name: contact
      pre: '#'
      url: contact
      weight: 7
    - name: themefisher
      pre: ''
      url: 'https://themefisher.com/'
      weight: 8
Languages:
  pt:
    languageName: Pt-br
    languageCode: pt-br
    contentDir: content/portuguese
    weight: 1
    home: Home
    copyright: >-
      Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) &
      Developed by [Gethugothemes](https://gethugothemes.com)
  en:
    languageName: En
    languageCode: en-us
    contentDir: content/english
    weight: 1
    home: Home
    copyright: >-
      Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) &
      Developed by [Gethugothemes](https://gethugothemes.com)
 
